name: Feature request
description: File a new feature request
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request
  - type: textarea
    id: feature
    attributes:
      label: Feature description
      description: Please describe the behavior you'd like to see.
    validations:
      required: true
  - type: textarea
    id: problem-usecase
    attributes:
      label: Problem or use case
      description: Please explain which problem this would solve, or what the use case is for the feature. Keep in mind that it's more likely to be implemented if it's generally useful for a larger number of users.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds
      description: Please describe any alternatives or workarounds you have considered and, possibly, rejected.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
